# Generated by Django 5.2 on 2026-01-08 09:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavEdgesFinal',
            fields=[
                ('ogc_fid', models.IntegerField(primary_key=True, serialize=False)),
                ('source', models.IntegerField()),
                ('target', models.IntegerField()),
                ('cost', models.FloatField()),
                ('wkb_geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'db_table': 'nav_edges_final',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NavEdgesWorkVerticesPgr',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('the_geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'nav_edges_work_vertices_pgr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomPoint',
            fields=[
                ('ogc_fid', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('wkb_geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'room_points',
                'managed': False,
            },
        ),
    ]
